### ISSUE TITLE
Failure sending transaction: Value offset out of range

### ISSUE THREAD

**Issue by mgild** [solana-labs/solana-web3.js#1026]
``` 
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 1231. Received 1232
     at boundsError (internal/buffer.js:82:9)
     at writeU_Int8 (internal/buffer.js:737:5)
     at Buffer.writeUIntLE (internal/buffer.js:648:12)
     at UInt.encode (/node_modules/buffer-layout/lib/Layout.js:580:7)
     at /node_modules/buffer-layout/lib/Layout.js:1117:25
     at Buffer.reduce (<anonymous>)
     at Sequence.encode (/node_modules/buffer-layout/lib/Layout.js:1116:22)
     at Structure.encode (/node_modules/buffer-layout/lib/Layout.js:1272:26)
     at /node_modules/@solana/web3.js/src/message.ts:137:40
     at Array.forEach (<anonymous>) {
   code: 'ERR_OUT_OF_RANGE'
 }
 [Error] Failed to fulfill transaction

```

**Comment by jstarry** [comment]
Thanks @mgild working on adding a better error for this. The issue is that one of the instructions is bigger than 1232 bytes. That means it's really quite big since the whole transaction (including signatures, pubkeys, headers, and instructions) cannot exceed 1232 bytes
