### ISSUE TITLE
"load BPF Rust program" test fails

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana-web3.js#493]
Seen in CI and locally against `npm run localnet:up`

Failure:
```
● load BPF Rust program

    Transaction 2PdAGNXcpGjB28nAQ6jfMtaDkkaeJJ3z6BqfSxhy9a8VQdQdbkhwKdmLwTJtMDbrtnw1LMn2o9pRbFYz99KjviEh failed ({"Err":{"InstructionError":[0,"GenericError"]}})

      53 |
      54 |     if (status && status.Err && !('AccountInUse' in status.Err)) {
    > 55 |       throw new Error(
         |             ^
      56 |         `Transaction ${signature} failed (${JSON.stringify(status)})`,
      57 |       );
      58 |     }

      at _callee$ (src/util/send-and-confirm-transaction.js:55:13)
      at tryCatch (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

**Comment by CriesofCarrots** [comment]
Fixed by #494
